### ISSUE TITLE
403 on app_dev.php

### ISSUE THREAD

**Issue by manuelDistefano** [maxpou/docker-symfony#30]
I cant access to symfony.dev/app_dev.php, i get 403.
I'm on ubuntu and need to run docker with sudo (sudo docker-compose up) or i have:

"ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable."

Unfortunately cache in prod env make me crazy

Can you help me?

**Comment by leroy0211** [comment]
You have having 2 different issues. One related to your docker host, and one to your symfony.

You cannot access `app_dev.php` because symfony has a security built-in. Open the app_dev.php and you should see some code which will block direct access from anything not localhost. Your pc (host) is not the localhost for the docker container. Which means you have to add your host ip-address, or just remove the security check. 


Your other issue about the docker daemon is that your user is not in the docker group. Just add your user to the docker group and restart your shell (http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo)

```
sudo usermod -aG docker $USER
```

**Comment by manuelDistefano** [comment]
Hi @leroy0211 

yeah i made some digging and now i can access to app_dev.php ;)  At the moment i just set app_dev.php like app.php.

I didn't know about the user in the docker group. I will set it.
Thankyou!

**Comment by leroy0211** [comment]
Great!

Make sure you keep the next code in place! Otherwise you will load your `prod` configuration instead of the `dev` configuration. 

```php
$kernel = new AppKernel('dev', true);
```

**Comment by maxpou** [comment]
@manuelDistefano one last thing, don't commit/push your app_dev.php in production 😉

**Comment by manuelDistefano** [comment]
Yeah i excluded app_dev.php from staging/production repository, i will use it only in my local env.

Tnx!
